### ISSUE TITLE
Unable to load DLL 'PixGL.dll'

### ISSUE THREAD

**Issue by jmcglory** [thomasjo/highlight#10]
I get this error..A google of the dll returns nothing! What am I missing?

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'PixGL.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=PixelEngine
  StackTrace:
   at PixelEngine.Windows.SetValues(Single pw, Single ph, Single ww, Single wh)
   at PixelEngine.OpenGL.Initialize(Sprite drawTarget, Sprite textTarget)
   at PixelEngine.Game.GameLoop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by jmcglory** [comment]
sorry wrong place
